spring.application.name=apartment-management
spring.datasource.url=jdbc:h2:mem:apartmentdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Prometheus ve Grafana Metrik Takip
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

aws.access-key=YOUR_ACCESS_KEY
aws.secret-key=YOUR_SECRET_KEY
aws.region=us-east-1
aws.s3.bucket=my-apartment-bucket

# Disable swagger-ui for production profile
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.security.user.name=admin
spring.security.user.password=123456